### ISSUE TITLE
Add functionality to download AsyncAPI spec from EP after successful import

### ISSUE THREAD

**Issue by TamimiGitHub** [SolaceLabs/ep-asyncapi-importer-typescript#26]
Feature: download the AsyncAPI spec file from EP into the output folder.

Blocker: Waiting on EP team to fix issue with downloading AsyncAPI spec file.

**Comment by TamimiGitHub** [comment]
How will this impact non solace specific extensions?

**Comment by ricardojosegomezulmke** [comment]
added in release 0.8.1-alpha.
